name: Publish

on:
  push:
    branches:
      - 11-alpha

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Restore Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execution permission to Gradle Wrapper
        run: chmod +x gradlew
      - name: Build release APK
        run: ./gradlew assembleLawnWithQuickstepRelease
      - name: Sign release APK
        uses: r0adkll/sign-android-release@v1
        id: sign-release-apk
        with:
          releaseDirectory: build/outputs/apk/lawnWithQuickstep/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Release APK
          path: ${{ steps.sign-release-apk.outputs.signedReleaseFile }}
  upload-apk:
    runs-on: ubuntu-latest
    needs: build-release-apk
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: Release APK
          path: artifacts/release-apk
      - name: Create tag name
        id: tag-name
        run: |
          echo "::set-output name=name::11-alpha-$(date +'%Y%m%d')-$(git rev-parse --short $GITHUB_SHA)"
          echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Push tag
        run: |
          git tag ${{ steps.tag-name.outputs.name }}
          git push origin ${{ steps.tag-name.outputs.name }}
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: artifacts/release-apk/**.apk
          commit: ${{ github.sha }}
          tag: ${{ steps.tag-name.outputs.name }}
          name: Nightly build of 11-alpha (${{ github.sha }}) on ${{ steps.tag-name.outputs.date }}
          body: |
            |             |                                    |
            |-------------|------------------------------------|
            | Branch      | 11-alpha                           |
            | Commit hash | ${{ github.sha }}                  |
            | Date        | ${{ steps.tag-name.outputs.date }} |
          token: ${{ secrets.GITHUB_TOKEN }}
